npx ascii-art install roman
npx ascii-art install big
npx ascii-art install basic
npx ascii-art install computer
npx ascii-art install cybersmall
npx ascii-art install cybermedium
npx ascii-art install cyberlarge
npx ascii-art install doh
npx ascii-art install block
npx ascii-art install colossal
npx ascii-art install o8
npx ascii-art install rozzo
